-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."softCartDimDate"
(
    dateid integer NOT NULL,
    year integer,
    month integer,
    monthname character varying,
    weekday integer,
    weekdayname character varying,
    PRIMARY KEY (dateid)
);

CREATE TABLE IF NOT EXISTS public."softCartDimCategory"
(
    cartegoryid integer NOT NULL,
    category_name character varying,
    PRIMARY KEY (cartegoryid)
);

CREATE TABLE IF NOT EXISTS public."softcartDimCountry"
(
    countryid integer NOT NULL,
    country_name character varying,
    PRIMARY KEY (countryid)
);

CREATE TABLE IF NOT EXISTS public."softCartDimItem"
(
    itemid integer NOT NULL,
    item_name character varying,
    PRIMARY KEY (itemid)
);

CREATE TABLE IF NOT EXISTS public."softCartFactSales"
(
    orderid integer NOT NULL,
    item_id integer,
    country_id integer,
    cartegory_id integer,
    date_id integer,
    price integer,
    PRIMARY KEY (orderid)
);

ALTER TABLE IF EXISTS public."softCartFactSales"
    ADD CONSTRAINT datefk FOREIGN KEY (date_id)
    REFERENCES public."softCartDimDate" (dateid) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."softCartFactSales"
    ADD CONSTRAINT itemfk FOREIGN KEY (item_id)
    REFERENCES public."softCartDimItem" (itemid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softCartFactSales"
    ADD CONSTRAINT cartegoryfk FOREIGN KEY (cartegory_id)
    REFERENCES public."softCartDimCategory" (cartegoryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softCartFactSales"
    ADD CONSTRAINT countryfk FOREIGN KEY (country_id)
    REFERENCES public."softcartDimCountry" (countryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;